# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.3"

  config.vm.define :server do |host|
    _HOSTNAME = "server"
    _PRIVATE_IP_ADDRESS = "192.168.33.10"

    host.vm.hostname = _HOSTNAME
    host.vm.network "private_network", ip: _PRIVATE_IP_ADDRESS
    host.vm.provision :shell, path: "stop-security.sh"
    host.vm.provision :shell, path: "set-sshkey.sh"
    host.vm.provision :shell, path: "install-golang.sh"
    host.vm.provision :shell, path: "install-vuls.sh"
  end
end
