# [slack]
# hookURL      = "https://hooks.slack.com/services/XXXXXXXXX/XXXXXXX/XXXXXXXXXXXXXXXXX"
# channel      = "#vuls"
# iconEmoji    = ":ghost:"
# authUser     = "vuls"
# notifyUsers  = ["@here"]

[servers]

[servers.sample]
host         = "HOST"
port         = "PORT"
user         = "USER"
keyPath      = "/root/.ssh/private_key"
